# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment"
client_id = "bb419c85328cbab0d9208ab547b434d6"
application_url = "https://spiritual-holmes-privilege-louisiana.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://spiritual-holmes-privilege-louisiana.trycloudflare.com/auth/callback",
  "https://spiritual-holmes-privilege-louisiana.trycloudflare.com/auth/shopify/callback",
  "https://spiritual-holmes-privilege-louisiana.trycloudflare.com/api/auth/callback",
  "https://spiritual-holmes-privilege-louisiana.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-58.myshopify.com"
